name: drag_and_drop_generator
description: Generate all nodes for the drag and drop interface.
# version: 1.0.0

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  code_builder: ^3.5.0
  dart_style: ^1.3.8
  http: ^0.12.2

dev_dependencies:
  effective_dart: ^1.2.4
  test: ^1.15.4
